-- Extruder Jobs
CREATE TABLE IF NOT EXISTS public.extruder_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id UUID REFERENCES public.production_machines(id) ON DELETE CASCADE,
    product_code TEXT,
    product_name TEXT,
    surface TEXT,
    thickness TEXT,
    coil_width TEXT,
    quantity NUMERIC NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'pending',
    display_order NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pattern Jobs
CREATE TABLE IF NOT EXISTS public.pattern_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id UUID REFERENCES public.production_machines(id) ON DELETE CASCADE,
    product_code TEXT,
    product_name TEXT,
    surface TEXT,
    thickness TEXT,
    coil_width TEXT,
    quantity NUMERIC NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'pending',
    display_order NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Cutting Jobs
CREATE TABLE IF NOT EXISTS public.cutting_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id UUID REFERENCES public.production_machines(id) ON DELETE CASCADE,
    product_code TEXT,
    product_name TEXT,
    surface TEXT,
    thickness TEXT,
    coil_width TEXT,
    quantity NUMERIC NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'pending',
    display_order NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
